name: Test & Build

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]

jobs:
  test:
    name: Test
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: docker build --build-arg TARGETPLATFORM=linux/amd64 --target test .

  build:
    name: Build
    runs-on: [self-hosted, linux]
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: secondlife/action-build-docker@v1
        with:
          image: platform/nginx-proxy 
          platforms: linux/amd64,linux/arm64
          promote: ${{ startsWith(github.ref, 'refs/tags/v') }}
          jfrog-token: ${{ secrets.SHARED_JFROG_TOKEN }}
